### ISSUE TITLE
[object Promise] instead of rendering

### ISSUE THREAD

**Issue by quinnanya** [Savjee/eleventy-plugin-bibtex#1]
Hi, thank you so much for creating this! It's exactly what I'm looking for.

I followed the setup instructions, but instead of getting the HTML for the citation, it's just displaying "[object Promise]" for each citation. Googling around it seems to have something to do with asynchronous loading, but I can't quite work out how to fix it. Any ideas would be wonderful!

**Comment by Savjee** [comment]
The function is indeed asynchronous, but I don't understand why you get that output.
Which template language are you using? I'm personally using Liquid, and it works out of the box. Perhaps other templating languages require some more work.

**Comment by quinnanya** [comment]
Thank you! I was using nunjucks and didn't realize that would make a difference. I added `templateEngineOverride: liquid` to the template frontmatter and changed the file extension, and now it's working perfectly!

**Comment by tommasoturchi** [comment]
Just for future reference, if you want to make the plugin work for current 11ty/nunjucks, here's the config for .eleventy.js:

```
eleventyConfig.addPairedAsyncShortcode(
    "bibtex",
    require("eleventy-plugin-bibtex")
  );
```

**Comment by Savjee** [comment]
@tommasoturchi Thanks for this! I've added your snippet to the README file ;)
